server:
  port: 0  # it will take randomly generated available port

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_db
    username: postgres
    password: admin123

    hikari:
      minimum-idle: 2
      maximum-pool-size: 10

app:
  service-name: Identity Service
  message: Identity configuration loaded from GitHub

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
