server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: admin123

    hikari:
      minimum-idle: 2
      maximum-pool-size: 10

app:
  service-name: Payment Service
  message: Payment configuration loaded from GitHub
